spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ssgt
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

jwt:
  secret: ${JWT_SECRET:9fK7xP2mQ8vL1sNc4TzR6wHy3BdEa7JuX5kMn0CpVg}